### ISSUE TITLE
How to have [AllowAnonymous] attribute on a web api while rest of application still using basic authentication?

### ISSUE THREAD

**Issue by stefanzvonar** [nabehiro/HttpAuthModule#14]
Enjoy this library.  However, if I want to have one Web API method in the application be allowed with [AllowAnonymous] but have the rest of the application / api's be locked down with Basic Authentication, can this be done (without having to disable the entire module in the web.config app settings)?

**Comment by stefanzvonar** [comment]
Actually, I think I may be able to configure it with the IgnorePathRegex appSetting anyway :)

**Comment by nabehiro** [comment]
Hi, HttpAuthModule authentication is indepent of ASP.NET standard mechanism (Authorize attribute, AllowAnonymous attribute).

I think you can allow anonymous access of specified URLs using IgnorePathRegex setting.
