### ISSUE TITLE
Allow Credentials to be set in <appSettings> ?

### ISSUE THREAD

**Issue by garychapman** [nabehiro/HttpAuthModule#6]
I have several Azure sites and I'd like set different credentials for each one (using web.config transformations can be slow and error-prone).

Would it be possible to read a Credentials string from \<appSettings\> and include them with those already in the \<httpAuthModule\> section?

Thanks for writing HttpAuthModule!

**Comment by nabehiro** [comment]
I modified HttpAuthModule to enable settings to be configured on appSettings.

https://github.com/nabehiro/HttpAuthModule#configuration

thanks for feedback.

**Comment by garychapman** [comment]
Works perfectly! Thanks for such a quick turnaround :-)
