### ISSUE TITLE
The provided URI scheme 'https' is invalid; expected 'http'. web service Digest authentication

### ISSUE THREAD

**Issue by dotnet86** [nabehiro/HttpAuthModule#7]
Hello,

when i have used HTTPS web service url then system occurred error : "The provided URI scheme 'https' is invalid; expected 'http'". it's working fine with "HTTP". Following my App.config setting where i calling that web service.
    
```
<security mode="TransportCredentialOnly">
            <transport clientCredentialType="Digest" proxyCredentialType="Digest"/>
</security>

<behaviors>
      <endpointBehaviors>
        <behavior name="impersonationBehavior">
          <clientCredentials>
            <httpDigest impersonationLevel="Impersonation"/>
          </clientCredentials>
        </behavior>
      </endpointBehaviors>
    </behaviors>
```

Waiting for your valuable reply
Thank you

**Comment by nabehiro** [comment]
Hi, dotnet86.

I haven't used HttpAuthModule with WCF.
Seeing your config setting,  I feel that WCF's Digest Authentication is activated.
I guess that HttpAuthModule's authentication and WCF's one can't be activated together.
