### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by ExileBLR** [nabehiro/HttpAuthModule#8]
It would be great if you could add a license to your module. Here's [an example](https://github.com/dotnet/corefx#license). Just to be sure that we can use it in our software. Thanks!

**Comment by nabehiro** [comment]
Thank you for pointing it out.
I added a license.
https://github.com/nabehiro/HttpAuthModule/blob/master/LICENSE

**Comment by ExileBLR** [comment]
Thank you, problem solved :)
