### ISSUE TITLE
Microsoft Edge 対応

### ISSUE THREAD

**Issue by yamashinya** [nabehiro/HttpAuthModule#9]
Microsoft Edge でアクセスすると認証ダイアログは表示されますが認証できません

**Comment by nabehiro** [comment]
[Microsoft Edge においてダイジェスト認証を完了できない場合があります](https://support.microsoft.com/ja-jp/kb/3163423)

が原因と思われます。
クライアントが Edge で利用する場合、ダイジェスト認証ではなくベーシック認証を利用したほうがよろしいかと思います。
